In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Anemia_menor_36m_2025.csv', sep=';', encoding='latin1')
df.head()

,Fecha_Atencion,RENIPRESS,IPRESS,Id_Genero,Edad_meses,Diagnostico
0,7/03/2025,2864,HOSPITAL HIPOLITO UNANUE DE TACNA,M,12,Sin Anemia
1,7/03/2025,2864,HOSPITAL HIPOLITO UNANUE DE TACNA,M,12,Sin Anemia
2,1/04/2025,2864,HOSPITAL HIPOLITO UNANUE DE TACNA,F,13,Sin Anemia
3,10/04/2025,2864,HOSPITAL HIPOLITO UNANUE DE TACNA,F,12,Sin Anemia
4,20/10/2025,2864,HOSPITAL HIPOLITO UNANUE DE TACNA,F,18,Sin Anemia

In [3]:
df.shape

(5343, 6)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5343 entries, 0 to 5342
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Fecha_Atencion  5343 non-null   object
 1   RENIPRESS       5343 non-null   int64
 2   IPRESS          5343 non-null   object
 3   Id_Genero       5343 non-null   object
 4   Edad_meses      5343 non-null   int64
 5   Diagnostico     5343 non-null   object
dtypes: int64(2), object(4)
memory usage: 250.6+ KB

In [5]:
renombrar = {
    'Fecha_Atencion': 'fecha_atencion',
    'RENIPRESS': 'renipress',
    'IPRESS': 'ipress',
    'Id_Genero': 'genero',
    'Edad_meses': 'edad',
    'Diagnostico': 'diagnostico'
}

In [6]:
df = df.rename(columns=renombrar)
df.head()

,fecha_atencion,renipress,ipress,genero,edad,diagnostico
0,7/03/2025,2864,HOSPITAL HIPOLITO UNANUE DE TACNA,M,12,Sin Anemia
1,7/03/2025,2864,HOSPITAL HIPOLITO UNANUE DE TACNA,M,12,Sin Anemia
2,1/04/2025,2864,HOSPITAL HIPOLITO UNANUE DE TACNA,F,13,Sin Anemia
3,10/04/2025,2864,HOSPITAL HIPOLITO UNANUE DE TACNA,F,12,Sin Anemia
4,20/10/2025,2864,HOSPITAL HIPOLITO UNANUE DE TACNA,F,18,Sin Anemia

In [7]:
df['fecha_atencion'] = pd.to_datetime(df['fecha_atencion'], errors='coerce', dayfirst=True)

In [8]:
df[['renipress', 'ipress', 'genero', 'diagnostico']] = df[['renipress', 'ipress', 'genero', 'diagnostico']].astype('string')

In [11]:
df.describe(include='number')

              edad
count  5343.000000
mean     18.842972
std       7.976909
min       6.000000
25%      12.000000
50%      19.000000
75%      24.000000
max      35.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5343 entries, 0 to 5342
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fecha_atencion  5343 non-null   datetime64[ns]
 1   renipress       5343 non-null   string
 2   ipress          5343 non-null   string
 3   genero          5343 non-null   string
 4   edad            5343 non-null   int64
 5   diagnostico     5343 non-null   string
dtypes: datetime64[ns](1), int64(1), string(4)
memory usage: 250.6 KB